[tool.ruff]
line-length = 80
indent-width = 2

[tool.ruff.format]
quote-style = "double"
skip-magic-trailing-comma = false

[tool.coverage.run]
include = ["src/*"]

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
pythonpath = ["src"]